#server:
#  port: 8081

springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /api-docs

spring:
  mongodb:
    embedded:
      version: 4.0.21

  data:
    mongodb:
      uri: mongodb+srv://mongodb:Link%4012345@cluster0.ofyln36.mongodb.net/?tls=true&tlsInsecure=true&connectTimeoutMS=5000&socketTimeoutMS=10000&retryWrites=true&w=majority
      database: sample_training

data:
  default-page-size: 500

#azure:
#  activedirectory:
#    client-id: 0e15ebd5-a17e-4e53-ab42-dac9cd690d19
#    app-id-uri: api://0e15ebd5-a17e-4e53-ab42-dac9cd690d19
#    tenant-id: c596bb4b-3af1-420f-89f1-672f8c6dce60